#!/bin/bash

PROMPT_COLOR_BLUE='\[\e[0;34m\]'
PROMPT_COLOR_LIGHT_BLUE='\[\e[1;34m\]'
PROMPT_COLOR_PURPLE='\[\e[0;35m\]'
PROMPT_COLOR_LIGHT_PURPLE='\[\e[1;35m\]'
PROMPT_COLOR_RED='\[\e[0;31m\]'
PROMPT_COLOR_LIGHT_RED='\[\e[1;31m\]'
PROMPT_COLOR_GREEN='\[\e[0;32m\]'
PROMPT_COLOR_LIGHT_GREEN='\[\e[1;32m\]'
PROMPT_COLOR_YELLOW='\[\e[0;33m\]'
PROMPT_COLOR_LIGHT_YELLOW='\[\e[1;33m\]'
PROMPT_COLOR_WHITE='\[\e[1;37m\]'
PROMPT_COLOR_LIGHT_GRAY='\[\e[0;37m\]'
PROMPT_COLOR_GRAY='\[\e[1;30m\]'
PROMPT_COLOR_LIGHT_CYAN='\[\e[0;36m\]'
PROMPT_COLOR_CYAN='\[\e[1;36m\]'
PROMPT_COLOR_RESET='\[\e[0m\]'

# Highlighted
PROMPT_COLOR_YELLOW_HL='\[\e[0;30;43m\]'
PROMPT_COLOR_RED_HL='\[\e[1;97;101m\]'

# Blinking
PROMPT_COLOR_YELLOW_BL='\[\e[5;30;43m\]'
